# If this is set to false, players will have to use /bulkminer
# before the plugin takes effect.
enabled-by-default: true

# If this is true, the plugin will not have any effect when
# the player is in a gamemode other than survival.
survival-only: true

# If this is false, blocks broken with the plugin will not drop
# experience, even if they would when broken normally.
drop-xp: true

# Blocks farther than this distance from the block broken by
# the player will be ignored.
# Setting this to large numbers is not recommended.
max-distance: 5

# The messages players see when using /bulkminer.
# Formatting is supported using &
message-enabled: "&a⛏&r BulkMiner &aenabled"
message-disabled: "&c⛏&r BulkMiner &cdisabled"
message-denied: "&cYou do not have permission to use this command."

# Blocks listed here may be broken en masse using BulkMiner.
# See here for a list of supported block IDs:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Generally, these IDs match Minecraft's block IDs, but in uppercase.
enabled-blocks:
- COAL_ORE
- COPPER_ORE
- DEEPSLATE_COAL_ORE
- DEEPSLATE_COPPER_ORE
- DEEPSLATE_DIAMOND_ORE
- DEEPSLATE_EMERALD_ORE
- DEEPSLATE_GOLD_ORE
- DEEPSLATE_IRON_ORE
- DEEPSLATE_LAPIS_ORE
- DEEPSLATE_REDSTONE_ORE
- DIAMOND_ORE
- EMERALD_ORE
- GOLD_ORE
- IRON_ORE
- LAPIS_ORE
- NETHER_GOLD_ORE
- NETHER_QUARTZ_ORE
- REDSTONE_ORE

# The plugin will only be triggered if the player is holding one of
# these items when breaking an enabled block.
# See here for a list of supported item IDs:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Generally, these IDs match Minecraft's item IDs, but in uppercase.
enabled-tools:
- DIAMOND_PICKAXE
- GOLDEN_PICKAXE
- IRON_PICKAXE
- NETHERITE_PICKAXE
- STONE_PICKAXE
- WOODEN_PICKAXE

# If this is true, the normal and deepslate variants of an ore are
# considered by the plugin to be the same block.
variants-are-same: true
